client/urls.py
from django.urls import path 

from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/comment/', views.clients_detail, name='comment'),
    path('<int:pk>/file/', views.clients_detail, name='file'),
    path('add/', views.clients_add, name='add'),
    path('export/', views.clients_export, name='export'),
]

lead/urls.py
from django.urls import path 

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('add', views.LeadCreateView.as_view(), name='add'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertLeadToClientView.as_view(), name='convert'),
    path('<int:pk>/file/', views.FileCreateView.as_view(), name='file'),
    path('<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment'),

]

tealcrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from user_profile.views import LogoutViaGet
from user_profile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('user_profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='user_profile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', LogoutViaGet.as_view(), name='logout'),
    # path('log-out/', LogoutViaGet.as_view(), name='logout'),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models
from django.contrib.auth.models import User

from team.models import Team


class Client(models.Model):
    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='clientfiles')
    created_by = models.ForeignKey(User, related_name='client_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)  

    
class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='client_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.user

client/forms.py
from django import forms 

from .models import Client, Comment, ClientFile

class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'description',)

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )


class AddFileForm(forms.ModelForm):
    class Meta:
        model = ClientFile
        fields = ('file', )

client/views.py
import csv

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Client
from .forms  import AddClientForm, AddCommentForm, AddFileForm

from team.models import Team

@login_required
def clients_list(request):
    clients = Client.objects.filter(created_by=request.user)

    return render(request, 'client/clients_list.html', {
        'clients': clients
    })


@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)

    comment_form = AddCommentForm()
    file_form = AddFileForm()

    if request.method == "POST":
        if 'submit_comment' in request.POST:
            comment_form = AddCommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.team = request.user.useprofile.active_team 
                comment.created_by = request.user
                comment.client = client
                comment.save()
                return redirect('clients:detail', pk=pk)

        elif 'submit_file' in request.POST:
            file_form = AddFileForm(request.POST, request.FILES)
            if file_form.is_valid():
                file = file_form.save(commit=False)
                file.team = request.user.useprofile.active_team
                file.client = client
                file.created_by = request.user
                file.save()
                return redirect('clients:detail', pk=pk)

    return render(request, 'client/clients_detail.html', {
        'client': client,
        'form': comment_form,
        'file_form': file_form,
    })


@login_required
def clients_add(request):
    team = request.user.useprofile.active_team

    if request.method == "POST":
        form = AddClientForm(request.POST)

        if form.is_valid():
            team = request.user.useprofile.active_team

            client = form.save(commit=False)
            client.created_by = request.user
            client.team = team
            client.save()

            messages.success(request, 'The client was created.')
 
            return redirect('clients:list')
    
    else:
        form = AddClientForm()

    return render(request, 'client/clients_add.html', {
        'form': form,
        'team': team,
        })


@login_required
def clients_delete(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    client.delete()

    messages.success(request, 'The client was deleted.')
    
    return redirect('clients:list')


@login_required
def clients_edit(request, pk):
    client = get_object_or_404(Client, pk=pk)

    if request.method == "POST":
        form = AddClientForm(request.POST, instance=client)

        if form.is_valid():
            form.save()

            messages.success(request, 'The changes was saved')

            return redirect('clients:list')
    else:
        form = AddClientForm(instance=client)

    return render(request, 'client/clients_edit.html', {
        'form': form,
        'client': client
    })


@login_required
def clients_export(request):
    clients = Client.objects.filter(created_by=request.user)

    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="clients.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(["Client", "Description", "Created at", "Created by"])

    for client in clients:
        writer.writerow((client.name, client.description, client.created_at, client.created_by))
    
    return response

client/templates/client/clients_add.html
{% extends "core/base.html" %}

{% block title %}
Add client
{% endblock %}


{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Add client</h1>

        {% if team.plan.max_clients > team.clients.all|length %}
            Num clients: {{ team.clients.all|length }}
            <form action="." method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
            </form>
        {% else %}
            <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
                Your team has reached maximum number of clients. Your owner must upgrade your plan! 
            </div>
        {% endif %}
    </div>
{% endblock %}

client/templates/client/clients_detail.html
{% extends "core/base.html" %}

{% block title %}
    {{ client.name }}
{% endblock %}


{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{ client.name }}</h1>

        {% if client.description %}
            <p class="font-semibold">Description</p>
            <p class="mb-2">{{ client.description }}</p>
        {% endif %}

        <p class="font-semibold">Created at</p>
        <p class="mb-2">{{ client.created_at }}</p>

        <p class="font-semibold">Modified at</p>
        <p class="mb-6">{{ client.modified_at }}</p>

        <hr class="my-4">

        <a href="{% url 'clients:delete' client.id %}" class="py-2 px-4 rounded-xl bg-red-500 text-white">Delete</a>
        <a href="{% url 'clients:edit' client.id %}" class="py-2 px-4 rounded-xl bg-red-500 text-white">Edit</a>

        <hr class="my-4">
            <h2 class="mb-6 text-xl">Comments</h2>
            <div class="space-y-4">
                {% for comment in client.comments.all %}
                    <div class="bg-gray-100 py-6 px-6 rounded-xl">
                        <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>
        
                        {{ comment.content }}
                    </div>
                {% endfor %}
            </div>

        <form action="{% url 'clients:comment' client.id %}" method="POST">
            {% csrf_token %}

            {{ form.as_p}}

            <button type="submit" name="submit_comment" class="py-2 px-4 rounded-xl bg-blue-500 text-white">Sumbit</button>
        </form>

        <hr class="my-4">
            <h2 class="mb-6 text-xl">Files</h2>
            <div class="space-y-4">
                {% for file in client.files.all %}
                    <div class="bg-gray-100 py-6 px-6 rounded-xl">
                        <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>
        
                        <a href="{{ file.file.url }}">Download</a>
                    </div>
                {% endfor %}
            </div>
            
            <div class="mt-2 mb-2">
                <form action="{% url 'clients:file' client.id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ file_form.as_p }}

                    <button type="submit" name="submit_file" class="py-2 px-4 rounded-xl bg-blue-500 text-white">Upload File</button>
                </form>
            </div>

        <hr class="my-4">

        <a href="{% url 'clients:list' %}">Back to clients</a>
    </div>
{% endblock %}

client/templates/client/clients_edit.html
{% extends "core/base.html" %}

{% block title %}
Edit client
{% endblock %}


{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Edit client</h1>

        <form action="{% url 'clients:edit' client.id %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
        </form>
    </div>
{% endblock %}

client/templates/client/clients_list.html
{% extends "core/base.html" %}

{% block title %}
Clients
{% endblock %}


{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">Clients</h1>

        <a href="{% url 'clients:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">
            Add Client
        </a>
        <a href="{% url 'clients:export' %}" class="inline-block py-4 px-6 rounded-xl bg-red-500 text-white">Export</a>
        {% if clients %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
            </div>
            {% for client in clients %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'clients:detail' client.id %}">{{ client.name }}</a>
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">There are no clients in database yet...</p>
        {% endif %}
    </div>
{% endblock %}