lead/urls.py
from django.urls import path 

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('add', views.LeadCreateView.as_view(), name='add'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertLeadToClientView.as_view(), name='convert'),
    path('<int:pk>/file/', views.FileCreateView.as_view(), name='file'),
    path('<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment'),

]

tealcrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from user_profile.views import LogoutViaGet
from user_profile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('user_profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='user_profile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', LogoutViaGet.as_view(), name='logout'),
    # path('log-out/', LogoutViaGet.as_view(), name='logout'),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lead/models.py
from django.db import models
from django.contrib.auth.models import User

from team.models import Team


class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    

class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='leadfiles')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)  

class Comment(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.user

lead/forms.py
from django import forms 

from .models import Lead, Comment, LeadFile

class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status')

class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )


class AddFileForm(forms.ModelForm):
    class Meta:
        model = LeadFile
        fields = ('file', )

lead/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin       
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django.views.generic.edit import DeleteView
from django.views import View

from .forms import AddCommentForm, AddFileForm
from .models import Lead, Comment as ClientComment

from client.models import Client
from team.models import Team


class LeadListView(LoginRequiredMixin, ListView):
    model = Lead
    template_name = 'lead/leads_list.html'
    context_object_name = 'leads'

    
    def get_queryset(self):
        queryset = super(LeadListView, self).get_queryset()
        queryset = queryset.filter(created_by=self.request.user, converted_to_client=False)

        return queryset

    
class LeadDetailView(LoginRequiredMixin, DetailView):
    model = Lead
    context_object_name = 'lead'
    template_name = 'lead/leads_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = AddCommentForm()
        context["fileform"] = AddFileForm()
        return context
    
    def get_queryset(self):
        queryset = super(LeadDetailView, self).get_queryset()
        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))


class LeadDeleteView(LoginRequiredMixin,DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
    
    def get_template_names(self):
        return []   

    
    def get_queryset(self):
        queryset = super(LeadDeleteView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))


class LeadUpdateView(LoginRequiredMixin,UpdateView):
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status')
    template_name = 'lead/leads_edit.html'
    success_url = reverse_lazy('leads:list')

    def get_queryset(self):
        queryset = super(LeadUpdateView, self).get_queryset()

        return queryset.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))
    

class LeadCreateView(LoginRequiredMixin, CreateView):
    model = Lead
    fields = ('name', 'email', 'description', 'priority', 'status')
    template_name = 'lead/leads_add.html'
    success_url = reverse_lazy('leads:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["team"] = self.request.user.useprofile.active_team
        return context
    
    def form_valid(self, form):
        team = team = self.request.user.useprofile.active_team

        if team.leads.count() >= team.plan.max_leads:
            messages.error(self.request, "You have reached the lead limit for your plan.")
            return redirect('leads:list')

        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.team = team
        self.object.save()
        
        messages.success(self.request, 'The lead was created.')
        return redirect(self.get_success_url())


class ConvertLeadToClientView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        lead = get_object_or_404(Lead, pk=pk, created_by=request.user)
        team = request.user.useprofile.active_team

        client = Client.objects.create(
            name=lead.name,
            email=lead.email,
            description=lead.description,
            created_by=request.user,
            team=team
        )

        lead.converted_to_client = True
        lead.save()

        comments = lead.comments.all()
        
        for comment in comments:
            ClientComment.objects.create(
                client = client,
                content = comment.content,
                created_by = comment.created_by,
                team = team
            )

        messages.success(request, 'The lead was converted to a client')
        return redirect('leads:list')
    

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddCommentForm(request.POST)

        if form.is_valid():
            team = request.user.useprofile.active_team
            comment = form.save(commit=False)
            comment.team = team 
            comment.created_by = request.user
            comment.lead_id = pk
            comment.save()

        return redirect('leads:detail', pk=pk)
    
class FileCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')

        form = AddFileForm(request.POST, request.FILES)

        if form.is_valid():
            team = request.user.useprofile.active_team
            file = form.save(commit=False)
            file.team = team
            file.lead_id = pk 
            file.created_by = request.user
            file.save()


        return redirect('leads:detail', pk=pk)

            

lead/templates/lead/add_lead.html
{% extends "core/base.html" %}

{% block title %}
Add lead
{% endblock %}


{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Add lead</h1>
        
        {% if team.plan.max_leads > team.leads.all|length %}
            Num leads: {{ team.leads.all|length }}
            <form action="{% url 'add-lead' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
            </form>
        {% else %}
            <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
                Your team has reached maximum number of . Your owner must upgrade your plan! 
            </div>
        {% endif %}
    </div>
{% endblock %}

lead/templates/lead/leads_add.html
{% extends "core/base.html" %}

{% block title %}
Add lead
{% endblock %}


{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Add lead</h1>
        
        {% if team.plan.max_leads > team.leads.count %}
            <div class="font-bold text-lg">{{ team.plan|title }} plan offers maximum: {{ team.plan.max_leads }}</div>
            <div class="font-bold text-lg">Current leads: {{ team.leads.count }}</div>
            <form action="{% url 'leads:add' %}" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
            </form>
        {% else %}
            <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
                Your team has reached maximum number of . Your owner must upgrade your plan! 
            </div>
        {% endif %}
    </div>
{% endblock %}

lead/templates/lead/leads_detail.html
{% extends "core/base.html" %}

{% block title %}
    {{ lead.name }}
{% endblock %}


{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{ lead.name }}</h1>

        {% if lead.description %}
            <p class="font-semibold">Name</p>
            <p class="mb-2">{{ lead.description }}</p>
        {% endif %}

        <p class="font-semibold">Priority</p>
        <p class="mb-2">{{ lead.get_priority_display }}</p>

        <p class="font-semibold">Status</p>
        <p class="mb-2">{{ lead.get_status_display }}</p>

        <p class="font-semibold">Created at</p>
        <p class="mb-2">{{ lead.created_at }}</p>

        <p class="font-semibold">Modified at</p>
        <p class="mb-6">{{ lead.modified_at }}</p>

        <hr class="my-4">

        <div class="flex items-center mt-4">
            <form id="convert_form_{{ lead.id }}" action="{% url 'leads:convert' lead.id %}" method="POST" class="inline mr-2">
                {% csrf_token %}
                <button type="submit" class="py-2 px-4 rounded-xl bg-blue-500 text-white">Convert to Client</button>
            </form>

            <a href="{% url 'leads:edit' lead.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white mr-2">Edit</a>

            <form id="lead_delete_form" action="{% url 'leads:delete' lead.pk %}" method="POST" class="inline">
                {% csrf_token %}
                <button type="submit" class="py-2 px-4 rounded-xl bg-red-500 text-white">Delete</button>
            </form>
        </div>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Comments</h2>

        <div class="space-y-4">
            {% for comment in lead.comments.all %}
                <div class="bg-gray-100 py-6 px-6 rounded-xl">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>
                    
                    {{ comment.content }}
                </div>
            {% endfor %}
        </div>

        <form action="{% url 'leads:comment' lead.id %}" method="POST">
            {% csrf_token %}

            {{ form.as_p}}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Sumbit</button>
        </form>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Files</h2>

        <div class="space-y-4">
            {% for file in lead.files.all %}
                <div class="bg-gray-100 py-6 px-6 rounded-xl">
                    <p class="mb-2"><strong>{{ file.created_by }}</strong> @ {{ file.created_at }}</p>
                    
                    <a href="{{ file.file.url }}">Download</a>
                </div>
            {% endfor %}
        </div>


        <form action="{% url 'leads:file' lead.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{ fileform.as_p}}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Sumbit</button>
        </form>

        <hr class="my-4">

        <a href="{% url 'leads:list' %}">Back to leads</a>
    </div>
{% endblock %}

lead/templates/lead/leads_edit.html
{% extends "core/base.html" %}

{% block title %}
Edit lead
{% endblock %}


{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">Edit lead</h1>

        <form action="{% url 'leads:edit' lead.id %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
        </form>
    </div>
{% endblock %}

lead/templates/lead/leads_list.html
{% extends "core/base.html" %}

{% block title %}
Leads
{% endblock %}


{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">Leads</h1>

        <a href="{% url 'leads:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">
            Add Lead
        </a>
        {% if leads %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
            </div>
            {% for lead in leads %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'leads:detail' pk=lead.id %}">{{ lead.name }}</a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_priority_display }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ lead.get_status_display }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">There are no leads in database yet...</p>
        {% endif %}
    </div>
{% endblock %}