client/urls.py
from django.urls import path 

from . import views

app_name = 'clients'

urlpatterns = [
    path('', views.clients_list, name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('<int:pk>/delete/', views.clients_delete, name='delete'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/comment/', views.clients_detail, name='comment'),
    path('<int:pk>/file/', views.clients_detail, name='file'),
    path('add/', views.clients_add, name='add'),
    path('export/', views.clients_export, name='export'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='index'),
]

lead/urls.py
from django.urls import path 

from . import views

app_name = 'leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('add', views.LeadCreateView.as_view(), name='add'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertLeadToClientView.as_view(), name='convert'),
    path('<int:pk>/file/', views.FileCreateView.as_view(), name='file'),
    path('<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment'),

]

tealcrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from user_profile.views import LogoutViaGet
from user_profile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('user_profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('log-in/', views.LoginView.as_view(template_name='user_profile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', LogoutViaGet.as_view(), name='logout'),
    # path('log-out/', LogoutViaGet.as_view(), name='logout'),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team/urls.py
from django.urls import path 

from . import views

app_name = 'team'

urlpatterns = [
    path('', views.teams_list, name='list'),
    path('<int:pk>/edit/', views.edit_team, name='edit'),
    path('<int:pk>/activate/', views.activate_team, name='activate'),
    path('<int:pk>/detail/', views.detail, name='detail'),
]

user_profile/urls.py
from django.urls import path

from . import views 

app_name = 'user_profile'

urlpatterns = [
    path('myaccount/', views.myaccount, name='myaccount'),
    path('sign-up/', views.signup, name='signup'),
]

core/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

def edit(request):
    pass

core/templates/core/partials/footer.html
        <footer class="py-8 text-center bg-gray-200">
            <p class="text-xs text-gray-700">Copyright (c) 2025 - Teal CRM</p>
        </footer>

core/templates/core/partials/nav.html
<nav class="py-6 px-6 flex justify-between bg-teal-500">
            <a href="/" class="text-white">Teal CRM</a>

            <div class="space-x-4">
            	<a href="{% url 'about' %}" class="text-white">About</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'team:detail' team.id %}" class="text-white">{{ team.name }}</a>
                    <a href="{% url 'dashboard:index' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Dashboard</a>
                    <a href="{% url 'leads:list' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Leads</a>
                    <a href="{% url 'clients:list' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Clients</a>
                    <a href="{% url 'user_profile:myaccount' %}" class="py-4 px-6 bg-teal-800 rounded-xl text-white">My account</a>
                {% else %}
                    <a href="{% url 'login' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Log in</a>
                    <a href="{% url 'user_profile:signup' %}" class="py-4 px-6 bg-teal-300 rounded-xl text-white">Sign up</a>
                {% endif %}
                
            </div>
        </nav>